# See https://pre-commit.com/#plugins
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        # See https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html
        args: [--skip=soweego/cli.py, --multi-line=5, --line-length=88]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [--in-place, --recursive, --remove-all-unused-imports, --remove-unused-variables]
# See https://pre-commit.ci/#configuration
ci:
  autofix_commit_msg: pre-commit automatic fixes
  autoupdate_commit_msg: pre-commit hooks automatic update
