# Use an official Python runtime as a parent image
FROM python:3.7

# Set the working directory to /app
WORKDIR /app

# Copy the requirement.txt file
COPY requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Run some configuration scripts
COPY docker/config/ /config/

RUN apt-get update && apt-get -y install jq less tmux
ADD https://raw.githubusercontent.com/marfox/dotfiles/master/debian.bashrc /root
ADD https://raw.githubusercontent.com/marfox/dotfiles/master/.bash_aliases /root
ADD https://raw.githubusercontent.com/marfox/dotfiles/master/.tmux.conf /root
RUN mv /root/debian.bashrc /root/.bashrc

WORKDIR /app/soweego/

# Run a BASH shell when the container launches
CMD ["/bin/bash"]

