# Use an official Python runtime as a parent image
FROM python:latest

# Set the working directory to /app
WORKDIR /app

# Copy the requirement.txt file
COPY requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run some configuration scripts
COPY scripts/docker/config/ /config/

RUN cd /config && sh run_all_folder_scripts.sh

# Run a BASH shell when the container launches
CMD ["/bin/bash"]
