#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Constants"""

# Keys
LAST_MODIFIED_KEY = 'last-modified'

ENVIRONMENT_KEY = 'ENVIRONMENT'
PROD_DB_KEY = 'PROD_DB'
TEST_DB_KEY = 'TEST_DB'

DB_ENGINE_KEY = 'DB_ENGINE'
USER_KEY = 'USER'
PASSWORD_KEY = 'PASSWORD'
HOST_KEY = 'HOST'

CREATE_DB_SCHEMA_KEY = "CREATE_DB_SCHEMA"
SEED_DB_SCHEMA_KEY = "SEED_DB"

# Environments
DEVELOPMENT = 'DEVELOPMENT'
PRODUCTION = 'PRODUCTION'
